#!/bin/bash

# 1. Load the theme variables
source "$HOME/.config/hypr/theming/theme.conf"

# Helper function to remove '#' for Hyprland
strip() {
    echo "${1//\#/}"
}

echo "Applying theme..."

# -----------------------------------------------------
# 2. Generate Hypr Config
# -----------------------------------------------------
cat > "$HOME/.config/hypr/theming/colors/colors.conf" <<EOF
# Auto-generated by apply-theme.sh

\$background = rgb($(strip $background))
\$foreground = rgb($(strip $foreground))

\$accent     = rgb($(strip $accent))
\$accent-alt = rgb($(strip $accent_alt))
\$warning    = rgb($(strip $warning))
\$error      = rgb($(strip $error))
\$success    = rgb($(strip $success))

\$color0 = rgb($(strip $color0))
\$color1 = rgb($(strip $color1))
\$color2 = rgb($(strip $color2))
\$color3 = rgb($(strip $color3))
\$color4 = rgb($(strip $color4))
\$color5 = rgb($(strip $color5))
\$color6 = rgb($(strip $color6))
\$color7 = rgb($(strip $color7))
EOF

echo "-> Generated Hyprland colors"

# -----------------------------------------------------
# 3. Generate CSS
# -----------------------------------------------------
cat > "$HOME/.config/hypr/theming/colors/colors.css" <<EOF
/* Auto-generated by apply-theme.sh */

@define-color background $background;
@define-color foreground $foreground;

@define-color accent     $accent;
@define-color accent-alt $accent_alt;
@define-color warning    $warning;
@define-color error      $error;
@define-color success    $success;

@define-color color0     $color0;
@define-color color1     $color1;
@define-color color2     $color2;
@define-color color3     $color3;
@define-color color4     $color4;
@define-color color5     $color5;
@define-color color6     $color6;
@define-color color7     $color7;
EOF

echo "-> Generated CSS colors"

# -----------------------------------------------------
# 4. Generate Kitty Config
# -----------------------------------------------------
# We map 8-15 to the same as 0-7 for safety
cat > "$HOME/.config/hypr/theming/colors/kitty-colors.conf" <<EOF
# Auto-generated by apply-theme.sh

background $background
foreground $foreground
selection_background $accent
selection_foreground $background
url_color $accent_alt
cursor $accent
cursor_text_color $background

# Black
color0 $color0
color8 $color8

# Red
color1 $color1
color9 $color9

# Green
color2 $color2
color10 $color10

# Yellow
color3 $color3
color11 $color11

# Blue
color4 $color4
color12 $color12

# Magenta
color5 $color5
color13 $color13

# Cyan
color6 $color6
color14 $color14

# White
color7 $color7
color15 $color15
EOF

echo "-> Generated Kitty colors"

# -----------------------------------------------------
# 5. Reload Applications
# -----------------------------------------------------

# Reload Hyprland (Instantly updates borders)
hyprctl reload > /dev/null
echo "-> Reloaded Hyprland"

# Reload Waybar (Instantly updates colors)
killall waybar && waybar & disown
echo "-> Restarted Waybar"

# Reload Kitty (Send signal to all kitty instances to reload config)
killall -SIGUSR1 kitty 2>/dev/null
echo "-> Reloaded Kitty instances"

# Notify user
notify-send "Theme Updated" "New colors applied successfully."