# -- Main Colors --
# Ensure you use quotes and the # symbol
background="#050505"
foreground="#ffe6e6"

accent="#ff3333"
accent_alt="#ff9900"

# -- Status Colors --
warning="#ffaa00"
error="#cc0000"
success="#55bb55"

# -- Palette (Color 0-7) --
color0="#101010"
color1="#cc0000"
color2="#55aa55"
color3="#d65d0e"
color4="#445588"
color5="#a020f0"
color6="#44aaaa"
color7="#bbbbbb"

# -- Palette (Color 8-15) --
color8="#303030"
color9="#ff4444"
color10="#55ff55"
color11="#ffcc00"
color12="#7788cc"
color13="#ff55ff"
color14="#44ffff"
color15="#ffffff"
